f=60
omega=2*pi*f
V_p=120
V_p_RMS=V_p/sqrt(2)
phi=0
R_Y=9
X_Y=12
Z_Y=R_Y+X_Y*i   
E_AN=V_p*exp(phi*i)
E_BN=V_p*exp((phi-deg2rad(120))*i)
E_CN=V_p*exp((phi+deg2rad(120))*i)
I_a=E_AN/Z_Y
I_b=E_BN/Z_Y
I_c=E_CN/Z_Y
I_a_RMS=abs(I_a)/sqrt(2)
I_b_RMS=abs(I_b)/sqrt(2)
I_c_RMS=abs(I_c)/sqrt(2)
I_n=I_a+I_b+I_c
theta=angle(E_AN)-angle(I_a)
P=3*V_p_RMS*abs(I_a)*cos(theta)
Q=3*E_AN*I_a_RMS*sin(theta)
S=sqrt(P^2+Q^2)
FP=P/S
FP2=1
S_i=P/FP2
Q_i=sqrt(S_i^2-P^2)
Q_c=Q-Q_i
C=Q_c/(3*omega*V_p_RMS^2)
t=linspace(1,1.03,100)
I_a_eq=abs(I_a)*cos(omega*t+angle(I_a))
I_b_eq=abs(I_b)*cos(omega*t+angle(I_b))
I_c_eq=abs(I_c)*cos(omega*t+angle(I_c))
I_a_RMS_const=ones(size(t))*I_a_RMS
I_b_RMS_const=ones(size(t))*I_b_RMS
I_c_RMS_const=ones(size(t))*I_c_RMS
plot(t,I_a_eq)
hold on
plot(t,I_b_eq)
plot(t,I_c_eq)
plot(t,I_a_RMS_const)
plot(t,I_b_RMS_const)
plot(t,I_c_RMS_const)
legend('I_a','I_b','I_c','{I_a}_{RMS}','{I_b}_{RMS}','{I_c}_{RMS}')
xlabel('t (s)')
ylabel('I (A)')
abs(I_a)
rad2deg(angle(I_a))
abs(I_b)
rad2deg(angle(I_b))
abs(I_c)
rad2deg(angle(I_c))